layout_spectrum: 0.9772344
typography_spectrum: 0.614998
color:
  lightness: 0.7722909
  brandStrength: 0.6756211
  saturation: 0.7019919
  rhythmicContrast: 0.0008913686
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Nomad
