layout_spectrum: 0.9772344
name: Nomad
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.4983137
color:
  brandStrength: 0.8558179
  lightness: 0.7833052
  saturation: 0.7019919
  rhythmicContrast: 0.0008913686
  brandColors:
    - '#FEFEFE'
    - '#303938'
    - '#D7E2DE'
    - '#E0BC9B'
    - '#B4916E'
