layout_spectrum: 0.75178
favicon: null
name: Nomad
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.6875
  lightness: 0.7833052
  saturation: 0.875
  rhythmicContrast: 0.25
  brandColors:
    - '#FEFEFE'
    - '#303938'
    - '#D7E2DE'
    - '#E0BC9B'
    - '#B4916E'
typography_spectrum: 0.4983137
