name: Nomad
favicon: null
layout_spectrum: 0.9772344
typography_spectrum: 0.4983137
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#ff0000'
    - '#fbff00'
    - '#ff9900'
    - '#009970'
  brandStrength: 0.6875
  lightness: 0.7833052
  saturation: 0.7019919
  rhythmicContrast: 0.0008913686
purpose: []
